name: Publish GitHub Actions Artifacts Example1

on:
  push:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

 build:

    runs-on: windows-latest
    

    steps:
    - name: Step 1 - Create a temporary artifact downloads folder
      run: mkdir downloads
    
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.0
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish . --no-build --output "downloads"
      
    - name: Step 3 - Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v3
      with: 
          name: assets-for-download.exe
          path: downloads
